services:
  mongo:
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
    restart: on-failure

  application:
    build: .
    volumes:
      - ./:/app
    ports:
      - '8080:8080'
    depends_on:
      - mongo
    restart: on-failure
    environment:
      - CONFIG_FILE=/app/config/config.yaml